workflows:
  android-build:
    name: BlazeLiveBot APK Build
    environment:
      android_signing:
        - my_keystore
    scripts:
      - name: Set gradlew permissions
        script: |
          chmod +x ./gradlew
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
