workflows:
  android-build:
    name: BlazeLiveBot APK Build
    environment:
      android_signing:
        - my_keystore
    scripts:
      - name: Set gradlew permissions
        script: |
          chmod +x ./gradlew
      - name: Clean project
        script: |
          ./gradlew clean
      - name: Build APK
        script: |
          ./gradlew :app:assembleRelease --warning-mode all
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
